version: '3.3'
services:
  jobs-test-3-11:
    build:
      context: .
      dockerfile: Dockerfile.3.11
    environment:
      REDIS_HOST: redis-data-storage
      REDIS_PORT: 6379
      REDIS_DB: 15
      PYTHONPATH: /app
    links:
      - redis-data-storage
  redis-data-storage:
    image: redis:7-bullseye
    ports:
      - "6379:6379"
    command: redis-server --save ""
