FROM python:3.11-bullseye

WORKDIR /app

COPY requirements.txt .

RUN python3.11 -m pip install -r requirements.txt
RUN python3.11 -m pip install sphinx twine

# need jobs.py
COPY setup.py .
COPY VERSION .
COPY jobs.py .

RUN true
# COPY conf.py .
COPY VERSION .
# COPY index.rst .
RUN true
COPY README.rst .
COPY _docs/ /app/_docs/

# Note: needs access to Redis; assumes localhost:6879
CMD ["python3.11", "-m", "test_jobs"]
